# Generated by Django 5.2.16 on 2026-08-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0001_initial'),
        ('indexing', '0002_addaliastask_status_createindextask_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReindexTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], default='created', help_text='execution status of this task', max_length=16)),
                ('index', models.ForeignKey(help_text='index on which this task is applied', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='es.index')),
                ('job', models.ForeignKey(help_text='job in which this task is run', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='indexing.indexjob')),
                ('source_index', models.ForeignKey(help_text='Index with source data', on_delete=django.db.models.deletion.CASCADE, to='es.index')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
