# Generated by Django 5.2.16 on 2026-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0003_reindextask'),
    ]

    operations = [
        migrations.AddField(
            model_name='createindextask',
            name='shard_count',
            field=models.IntegerField(default=1, help_text='number of primary shards to use for the index'),
        ),
    ]
