# Generated by Django 4.2.30 on 2026-06-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexing', '0002_addaliastask_status_createindextask_status_and_more'),
        ('es', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulateTokenIndexTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], default='created', help_text='execution status of this task', max_length=16)),
                ('index', models.ForeignKey(help_text='index on which this task is applied', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='es.index')),
                ('job', models.ForeignKey(help_text='job in which this task is run', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='indexing.indexjob')),
                ('source_index', models.ForeignKey(help_text='Index containing source data', on_delete=django.db.models.deletion.CASCADE, to='es.index')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreateTokenIndexTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], default='created', help_text='execution status of this task', max_length=16)),
                ('delete_existing', models.BooleanField(default=False, help_text='Delete index if it exists already')),
                ('index', models.ForeignKey(help_text='index on which this task is applied', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='es.index')),
                ('job', models.ForeignKey(help_text='job in which this task is run', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='indexing.indexjob')),
                ('source_index', models.ForeignKey(help_text='Index containing source data', on_delete=django.db.models.deletion.CASCADE, to='es.index')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
