# Generated by Django 4.2.30 on 2026-07-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='populatetokenindextask',
            name='threshold',
            field=models.IntegerField(default=0, help_text='Minimum frequency threshold (across the whole corpus) for tokens'),
        ),
    ]
