# Generated by Django 4.2.26 on 2025-12-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0037_alter_corpusconfiguration_data_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='es_index',
            field=models.SlugField(blank=True, help_text='name of the corpus index in elasticsearch; leave blank to auto-generate when indexing', max_length=126),
        ),
    ]
