# Generated by Django 4.2.26 on 2025-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0038_alter_corpusconfiguration_es_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusconfiguration',
            name='es_alias',
            field=models.SlugField(blank=True, help_text='additional alias for the corpus index in elasticsearch', max_length=126),
        ),
    ]
