# Generated by Django 5.2.17 on 2026-09-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0038_alter_corpusconfiguration_es_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='normalize_whitespace',
            field=models.BooleanField(default=True, help_text='Whether whitespace should be normalised in the interface. Only affects text content fields. Turn off to preserve whitespace; e.g. for poems/songs.'),
        ),
    ]
