# Generated by Django 5.2.16 on 2026-08-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcorpus', '0038_alter_corpusconfiguration_es_alias_and_more'),
        ('bow', '0001_initial'),
        ('es', '0001_initial'),
        ('indexing', '0002_addaliastask_status_createindextask_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populatebowindextask',
            name='index',
        ),
        migrations.RemoveField(
            model_name='populatebowindextask',
            name='job',
        ),
        migrations.RemoveField(
            model_name='populatebowindextask',
            name='source_index',
        ),
        migrations.CreateModel(
            name='AddBOWFieldTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], default='created', help_text='execution status of this task', max_length=16)),
                ('field', models.ForeignKey(help_text='Content field for which bag-of-word data is added', on_delete=django.db.models.deletion.CASCADE, to='addcorpus.field')),
                ('index', models.ForeignKey(help_text='index on which this task is applied', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='es.index')),
                ('job', models.ForeignKey(help_text='job in which this task is run', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='indexing.indexjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PopulateBOWFieldTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error'), ('aborted', 'Aborted'), ('cancelled', 'Cancelled')], default='created', help_text='execution status of this task', max_length=16)),
                ('threshold', models.IntegerField(default=0, help_text='Minimum frequency threshold (across the whole corpus) for tokens')),
                ('field', models.ForeignKey(help_text='Content field for which bag-of-word data is added', on_delete=django.db.models.deletion.CASCADE, to='addcorpus.field')),
                ('index', models.ForeignKey(help_text='index on which this task is applied', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='es.index')),
                ('job', models.ForeignKey(help_text='job in which this task is run', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='indexing.indexjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CreateBOWIndexTask',
        ),
        migrations.DeleteModel(
            name='PopulateBOWIndexTask',
        ),
    ]
