# Generated by Django 5.2.16 on 2026-08-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bow', '0002_remove_populatebowindextask_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populatebowfieldtask',
            name='threshold',
        ),
    ]
