# Generated by Django 4.2.30 on 2026-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_can_edit_corpora'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saml_username',
            field=models.CharField(blank=True, help_text='Username for SAML login', max_length=256, null=True, unique=True),
        ),
    ]
