# Generated by Django 4.2.30 on 2026-06-22 09:32

from django.db import migrations
from uuid import uuid4

def store_saml_username(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')

    saml_users = CustomUser.objects.filter(saml = True)

    for user in saml_users:
        user.saml_username = user.username
        user.username = uuid4()
        user.save()


def revert_saml_username(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')

    saml_users = CustomUser.objects.filter(saml = True)

    for user in saml_users:
        user.username = user.saml_username
        user.saml_username = None
        user.save()



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_saml_username'),
    ]

    operations = [
        migrations.RunPython(
            store_saml_username,
            reverse_code=revert_saml_username,
        )
    ]
